create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(254) NOT NULL,
  subscription_available BOOLEAN NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL unique (email)
);

create TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORY_NAME unique (name)
);

create TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat FLOAT(6) NOT NULL,
  lon FLOAT(6) NOT NULL,
  CONSTRAINT pk_location PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    initiator_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    location_id INTEGER NOT NULL,
    paid BOOLEAN NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    participant_limit INTEGER NOT NULL,
    creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    publication_date TIMESTAMP WITHOUT TIME ZONE,
    state VARCHAR(20) NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_initiator_id FOREIGN KEY(initiator_id)
    REFERENCES users(id),
    CONSTRAINT fk_category_id FOREIGN KEY(category_id)
    REFERENCES categories(id),
    CONSTRAINT fk_location_id FOREIGN KEY(location_id)
    REFERENCES locations(id)
);

create TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id INTEGER NOT NULL,
    event_id INTEGER NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_requester_id FOREIGN KEY(requester_id)
    REFERENCES users(id),
    CONSTRAINT fk_event_id FOREIGN KEY(event_id)
    REFERENCES events(id)
);

create TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

create TABLE IF NOT EXISTS compilation_events (
    compilation_id INTEGER NOT NULL,
    event_id INTEGER NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_id FOREIGN KEY(compilation_id)
    REFERENCES compilations(id),
    CONSTRAINT fk_event_id FOREIGN KEY(event_id)
    REFERENCES events(id)
);

create TABLE IF NOT EXISTS subscriptions (
    user_id INTEGER NOT NULL,
    subscribed_on INTEGER NOT NULL,
    CONSTRAINT pk_subscriptions PRIMARY KEY (user_id, subscribed_on),
    CONSTRAINT fk_user_id FOREIGN KEY(user_id)
    REFERENCES users(id),
    CONSTRAINT fk_subscribed_on FOREIGN KEY(subscribed_on)
    REFERENCES users(id)
);
